version: "3.7"
services:
  database:
      image: postgres:latest
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      volumes:
        - ./db/data:/var/lib/postgresql/data
        - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      ports:
        - '5432:5432'
      networks:
        - golang_balance

  go-docker-image:
      build: ./
      depends_on:
        - database
      ports:
        - '8010:8010'
      volumes:
        - ./:/app
      networks:
        - golang_balance

networks:
  golang_balance:
    driver: bridge